sonar.projectKey=pc-project-backend
sonar.projectName=PC Project Backend
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/kotlin
sonar.tests=src/test/kotlin
sonar.java.binaries=target/classes
sonar.junit.reportPaths=target/surefire-reports
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.host.url=https://im2ag-sonar.univ-grenoble-alpes.fr
