# R2DBC Configuration (reactive)
spring.r2dbc.url=r2dbc:postgresql://localhost:5432/airport
spring.r2dbc.username=postgres
spring.r2dbc.password=0205116969

# Flyway Configuration (blocking - for migrations)
spring.flyway.url=jdbc:postgresql://localhost:5432/airport
spring.flyway.user=postgres
spring.flyway.password=0205116969